### ISSUE TITLE
Need help converting Gridsize to float?

### ISSUE THREAD

**Issue by JustEvol12** [selfsame/unity-wave-function-collapse#11]
How would I convert Gridsize to float on all the script without getting errors? When I tried to change gridsize to a float in the Traning script, I get  

"error CS0266: Cannot implicitly convert type `float' to `int'. An explicit conversion exists (are you missing a cast?)" 

Not sure what to do.

I really need to make my character smaller than 1 meter.

**Comment by selfsame** [comment]
Yeah i have an issue open for that (https://github.com/selfsame/unity-wave-function-collapse/issues/9). In the meantime you'll probably have to use integer sized tiles and just resize the output map for your games needs
